### ISSUE TITLE
Dependency on specific levelup and leveldown versions

### ISSUE THREAD

**Issue by mitra42** [y-js/y-leveldb#1]
There appears to be a dependency in Y-leveldb on specific versions of levelup and leveldown that isn't captured by the dependency on level

levelup 2.0.0 wont work with Y-leveldb because it's constructor gets  passed the path of the directory holding the database rather than an object which is what it requires now. . 

I found that adding to my application's package.json
    "levelup": "^1.0.0-4",
    "leveldown": "^1.7.0-0",

It made sure Y-leveldb used the correct one, but I suspect that this dependency should be in Y instead. (or it should be fixed to work with levelup 2.0.0

**Comment by dmonad** [comment]
Hi @mitra42 ,

Thanks for the info. I will eventually update to levelup 2.0.0. But I don't have much time to invest in y-leveldb at the moment.

level@2.0 just release a few days ago. Unfortunately they didn't release a changelog, So I need to make sure that y-leveldb still works with level@2.0.

**Comment by mitra42** [comment]
Understood - in the meantime you should probably place those two lines above in package.json. (It took me several hours to diagnose this particular problem, and figure out a set that worked since different versions of levelup have a dependency on different versions of leveldown !

**Comment by dmonad** [comment]
Done. Thanks for the tip!
